/* shape group */
WALL_GROUP 		= 1;
CHARACTER_GROUP = 2;
BULLET_GROUP 	= 3;
DAMAGE_GROUP 	= 4;
FLOODER_GROUP 	= 5;
LIGHTBALL_GROUP = 6;
BLIND_GROUP 	= 7;
MANHOLE_GROUP 	= 8;

/* standard spec*/
FRAMERATE = Math.floor(1000/60);
ZOOM = 1.5;

/* character */
CHAR_SOUND_INT = 1.3;
CHAR_RAD = 12;
CHAR_LIFE = 0;
CHAR_VELOCITY = 1.5;
CHAR_DISTANCE = CHAR_RAD*1.45;

/* maze */
MAZE_SMALL_SQUARE = 20;
MAZE_BIG_SQUARE = 200;
MAZE_CHANCE_OF_BLIND = 0.3;
MAZE_MAX_BLIND = 5;
MAZE_NBR_OF_LIGHTBALL = 1;
MAZE_CHANCE_OF_MANHOLE = 0.1;

/* maze generator */
MG_RADIUS = 5;
MG_ROOM_NBR = 8;
MG_ROOM_SIZE = 6;

/* blind */
BL_RADIUS = 10;
BL_LIFE = 1;
BL_VELOCITY = 1;
BL_TIME_BETWEEN_DECISION = 100;
BL_SLEEPING_DISTANCE = 800;
BL_SOUND_RATIO = 1;
BL_ATTACK_DELAY = 100;

/* flooder */
FL_RADIUS = 10;
FL_LIFE = 1;
FL_DISTANCE = 20;
FL_VELOCITY = 1;
FL_LIFE_TIME = 3000;
FL_ATTACK_DELAY = 100;

/* lightball */
LI_RADIUS = 10;
LI_LIFE = 1;
LI_VELOCITY = 1.5;
LI_DISTANCE = 20;

/* manhole */
MH_DISTANCE = 2000;
MH_DELTA_TIME = 400;
MH_RADIUS = 20;
MH_LIFE = 1;

/* grenade launcher */
GL_RADIUS = 5;
GL_DAMAGE = 1;
GL_DAMAGE_RADIUS = 300;
GL_VELOCITY = 3;
GL_VELOCITY_TIME = 270;
GL_LIFE_TIME = 450;
GL_SOUND_INTENSITY = 6;
GL_RELOAD_TIME = 800;

/* shotgun */
SH_HEIGHT = 320;
SH_SMALL_WIDTH = 15;
SH_BIG_WIDTH = 100;
SH_DAMAGE = 1;
SH_RELOAD_TIME = 800;
SH_MAGAZIN = Infinity;
SH_SOUND_INTENSITY = 4;

/* punch */
PU_HEIGHT = 40;
PU_WIDTH = 20;
PU_DAMAGE = 1;
PU_RELOAD_TIME = 400;
PU_MAGAZIN = 1;
PU_SOUND_INTENSITY = 1;
